module.exports = {
  "ALIVE_IMG": "https://raw.githubusercontent.com/Niko-AND-Janiya/ANJU-DATA/refs/heads/main/WhatsApp%20Image%202024-09-08%20at%209.00.17%20PM.jpeg",
  "PREFIX": ".",
  "SESSION_ID" ANJU-MD=6YkT1DJT#j-i4LnPDwwpRor5vjRh5dbV-urleLYLxp_7RztwU53o,
  "AUTO_READ_STATUS": false,
  "MODE": "private",
  "BOT_NUMBER": "923071782626",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": false,
  "AUTO_VOICE": false,
  "AUTO_STICKER": false,
  "AUTO_REPLY": false,
  "AUTO_REACT": false,
  "WELCOME": false,
  "ANTI_BAD": false,
  "ANTI_BOT": false,
  "ANTI_LINK": false,
  "ALLWAYS_ONLINE": false,
  "MOROCCO_BLOCK": false,
  "BTN_MSG": false,
  "OWNER_NAME": "MR Raju",
  "NEWS_JID": "1234567890@s.whatsapp.net",
  "AUTO_TYPING": false,
  "AUTO_RECORDING": false,
  "AUTO_NEWS": false
};
